package pacman;

import pacman.framework.Animation;
import java.applet.Applet;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.applet.*;

public class StartingClass extends Applet implements Runnable, KeyListener {

	private static final long serialVersionUID = 1L;// generated by eclipse
	private Pacman pacman;
	private Image image, currentPacman, deadPacman, deadPacman2, point, ghost, block1, block2, block3, block4,
			currentBlock, gameOver, paused;
	private Graphics second;
	private URL base;
	private Animation animRight, animUp, animLeft, animDown;
	private boolean pacmanIsDead = false, pause = false, gameOverPlayed = false;
	private int startLives = 4;
	private int animSpeed = 5, score = 0, bestScore = 0, level = 0, lives = startLives;
	private String bestPlayer = null;
	private ArrayList<Point> points = new ArrayList<Point>();
	private ArrayList<Block> blocks = new ArrayList<Block>();
	private ArrayList<Ghost> ghosts = new ArrayList<Ghost>();
	private AudioClip coin, gameOverSound;

	@Override
	public void init() {
		setSize(720, 510);// 24[720px]_16[480px]|
		setBackground(Color.black);
		setFocusable(true);
		addKeyListener(this);
		Frame frame = (Frame) this.getParent().getParent();
		frame.setTitle("Pacman");

		try {
			base = getDocumentBase();
		} catch (Exception e) {
			// TODO: handle exception
		}

		// Image Setups
		animRight = new Animation();
		animUp = new Animation();
		animLeft = new Animation();
		animDown = new Animation();

		// load images for right direction
		animRight.addFrame(getImage(base, "data/rightstop.png"), animSpeed);
		animRight.addFrame(getImage(base, "data/right1.png"), animSpeed);
		animRight.addFrame(getImage(base, "data/right2.png"), animSpeed);
		animRight.addFrame(getImage(base, "data/right3.png"), animSpeed);
		animRight.addFrame(getImage(base, "data/right4.png"), animSpeed);

		// load images for left direction
		animLeft.addFrame(getImage(base, "data/leftstop.png"), animSpeed);
		animLeft.addFrame(getImage(base, "data/left1.png"), animSpeed);
		animLeft.addFrame(getImage(base, "data/left2.png"), animSpeed);
		animLeft.addFrame(getImage(base, "data/left3.png"), animSpeed);
		animLeft.addFrame(getImage(base, "data/left4.png"), animSpeed);

		// load images for up direction
		animUp.addFrame(getImage(base, "data/upstop.png"), animSpeed);
		animUp.addFrame(getImage(base, "data/up1.png"), animSpeed);
		animUp.addFrame(getImage(base, "data/up2.png"), animSpeed);
		animUp.addFrame(getImage(base, "data/up3.png"), animSpeed);
		animUp.addFrame(getImage(base, "data/up4.png"), animSpeed);

		// load images for down direction
		animDown.addFrame(getImage(base, "data/downstop.png"), animSpeed);
		animDown.addFrame(getImage(base, "data/down1.png"), animSpeed);
		animDown.addFrame(getImage(base, "data/down2.png"), animSpeed);
		animDown.addFrame(getImage(base, "data/down3.png"), animSpeed);
		animDown.addFrame(getImage(base, "data/down4.png"), animSpeed);

		currentPacman = animRight.getImage();
		point = getImage(base, "data/point.png");
		block1 = getImage(base, "data/block.png");
		block2 = getImage(base, "data/block2.png");
		block3 = getImage(base, "data/block3.png");
		block4 = getImage(base, "data/block4.png");
		ghost = getImage(base, "data/ghost.png");
		deadPacman = getImage(base, "data/deadpacman.png");
		// for paint lives in right down corner
		deadPacman2 = getImage(base, "data/deadpacman2.png");
		gameOver = getImage(base, "data/gameover.png");
		paused = getImage(base, "data/paused.png");

		coin = (AudioClip) getAudioClip(base, "data/coin.wav");
		gameOverSound = (AudioClip) getAudioClip(base, "data/gameover.wav");
		try {
			loadBestPlayer();// load from file
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	@Override
	public void start() {
		Thread thread = new Thread(this);
		thread.start();
	}

	@Override
	public void stop() {
		// TODO Auto-generated method stub
	}

	@Override
	public void destroy() {
		// TODO Auto-generated method stub
	}

	@Override
	public void run() {
		while (true) {// infinity game loop
			do {
				if (!pacmanIsDead) {
					level++;
					level = (level == 11) ? 1 : level;
					// level 1-10; 11 is not valid
					loadMap(level);

					while (points.size() != 0 && lives > 0) {
						if (!pause) {
							pacman.update();
							for (int i = 0; i < ghosts.size(); i++) {
								Ghost gh = (Ghost) ghosts.get(i);
								gh.update(pacman.getCenterX(), // collision
										pacman.getCenterY());// with border

								gh.ghostCollision(ghosts, blocks, i, pacman.getCenterX(), pacman.getCenterY());
								// pacmans death
								if (pacman.getRect().intersects(gh.getRect())) {
									reloadLevel();
								}
							}

							animate();// set currentPacman and give shut pacman
										// when he stop();
							pacmanPointCollision();
							pacmanBlockCollision();
						} // endif pause
						repaint();

						try {
							Thread.sleep(17);// 1000ms/17ms=59fps
						} catch (InterruptedException e) {
							e.printStackTrace();
						}
					}
				}
			} while (lives > 0);// game loop while pacman is alive

			pacmanIsDead = true;// for paint gameOver img
			currentPacman = deadPacman;
			if (!gameOverPlayed) {// play once time
				gameOverSound.play();
				gameOverPlayed = true;
			}
			repaint();

			if (bestPlayer == null && score == bestScore) {
				bestPlayer = JOptionPane.showInputDialog("enter your nickname");
				if (bestPlayer != null) {// for cancel
					bestPlayer = (bestPlayer.length() < 11) ? bestPlayer : bestPlayer.substring(0, 10);
					bestPlayer = (bestPlayer.length() == 0) ? null : bestPlayer;
				} else {
					bestPlayer = null;
				}
				// bestPlayer max length 10 else do substring length 10
				if (bestPlayer != null) {// do until player write something
					try {
						writeBestPlayer();
					} catch (IOException e) {
						e.printStackTrace();
					}
				}
			}
		}
	}

	public void animate() {// set currentPacman and give shut pacman
							// when he stop();
		animRight.update(2);
		animLeft.update(2);
		animUp.update(2);
		animDown.update(2);

		switch (pacman.getDirection()) {
		case 1:
			currentPacman = animUp.getImage();
			break;
		case 2:
			currentPacman = animDown.getImage();
			break;
		case 3:
			currentPacman = animLeft.getImage();
			break;
		case 4:
			currentPacman = animRight.getImage();
			break;
		}

		if (pacman.getSpeedX() == 0 && pacman.getSpeedY() == 0) {
			switch (pacman.getDirection()) {
			case 1:
				currentPacman = animUp.getImage(0);
				break;
			case 2:
				currentPacman = animDown.getImage(0);
				break;
			case 3:
				currentPacman = animLeft.getImage(0);
				break;
			case 0:
			case 4:
				currentPacman = animRight.getImage(0);
				break;
			}
		}
	}

	@Override
	public void update(Graphics g) {
		if (image == null) {
			image = createImage(this.getWidth(), this.getHeight());
			second = image.getGraphics();
		}

		second.setColor(getBackground());
		second.fillRect(0, 0, getWidth(), getHeight());// everything is black,
														// repaint all
		paint(second);

		g.drawImage(image, 0, 0, this);
	}

	@Override
	public void paint(Graphics g) {
		g.setFont(new Font("Ubuntu", Font.BOLD, 14));
		g.setColor(Color.LIGHT_GRAY);
		g.fillRect(0, 480, 720, 30);

		g.setColor(Color.white);
		g.fillRect(25, 485, 140, 20);
		g.fillRect(170, 485, 135, 20);
		g.fillRect(310, 485, 125, 20);

		g.setColor(Color.black);
		g.drawString((bestPlayer == null) ? "Not set" : bestPlayer, 30, 500);
		g.drawString("Record: " + bestScore, 175, 500);
		g.drawString("Score: " + score, 315, 500);

		for (int i = 0; i < points.size(); i++) {
			Point p = (Point) points.get(i);
			g.drawImage(point, p.getX() + 7, p.getY() + 7, this);
		}

		for (int i = 0; i < blocks.size(); i++) {
			Block b = (Block) blocks.get(i);
			g.drawImage(currentBlock, b.getX(), b.getY(), this);
		}

		for (int i = 0; i < ghosts.size(); i++) {
			Ghost gh = (Ghost) ghosts.get(i);
			g.drawImage(ghost, gh.getCenterX(), gh.getCenterY(), this);
		}

		for (int i = 0; i < lives; i++) {
			g.drawImage(deadPacman2, 600 + (i * 30), 484, this);
		}

		g.drawImage(currentPacman, pacman.getCenterX(), pacman.getCenterY(), this);

		if (pacmanIsDead) {
			pause = false;
			g.drawImage(gameOver, 0, 0, this);
		}

		if (pause) {
			g.drawImage(paused, 0, 0, this);
		}
	}

	@Override
	public void keyPressed(KeyEvent e) {
		if (pacman.getDirection() == 0) {// for start game
			switch (e.getKeyCode()) {
			case KeyEvent.VK_UP:
				if (pacman.getCanUp()) {
					pacman.setDirection(1);
					pacman.moveUp();
				}
				break;
			case KeyEvent.VK_DOWN:
				if (pacman.getCanDown()) {
					pacman.setDirection(2);
					pacman.moveDown();
				}
				break;
			case KeyEvent.VK_LEFT:
				if (pacman.getCanLeft()) {
					pacman.setDirection(3);
					pacman.moveLeft();
				}
				break;
			case KeyEvent.VK_RIGHT:
				if (pacman.getCanRight()) {
					pacman.setDirection(4);
					pacman.moveRight();
				}
				break;
			case KeyEvent.VK_R:
				restartGame();
				break;
			case KeyEvent.VK_P:
				pause = (pause) ? false : true;
				break;
			// cheats
			case KeyEvent.VK_J:// go to next level
				points.clear();
				break;
			case KeyEvent.VK_L:
				lives = 4;
				break;
			}

			for (int i = 0; i < ghosts.size(); i++) {
				Ghost gh = (Ghost) ghosts.get(i);
				switch (gh.getDirection()) {
				case 1:
					gh.moveUp();
					break;
				case 2:
					gh.moveDown();
					break;
				case 3:
					gh.moveLeft();
					break;
				case 4:
					gh.moveRight();
					break;
				}
			}
		} else {
			switch (e.getKeyCode()) {
			case KeyEvent.VK_UP:
				pacman.setChangeDirection(1);
				break;
			case KeyEvent.VK_DOWN:
				pacman.setChangeDirection(2);
				break;
			case KeyEvent.VK_LEFT:
				pacman.setChangeDirection(3);
				break;
			case KeyEvent.VK_RIGHT:
				pacman.setChangeDirection(4);
				break;
			case KeyEvent.VK_R:
				restartGame();
				break;
			case KeyEvent.VK_P:
				pause = (pause) ? false : true;
				break;
			}
		}
	}

	@Override
	public void keyReleased(KeyEvent e) {

	}

	@Override
	public void keyTyped(KeyEvent e) {

	}

	// methods for loadmap()
	public void addPoint(int x, int y) {
		Point p = new Point(x, y);
		points.add(p);
	}

	public void addBlock(int x, int y) {
		Block b = new Block(x, y);
		blocks.add(b);
	}

	public void addGhost(int x, int y) {
		Ghost gh = new Ghost(x, y);
		ghosts.add(gh);
	}

	public void pacmanPointCollision() {
		for (int i = 0; i < points.size(); i++) {
			Point p = (Point) points.get(i);
			if (pacman.getCenterX() == p.getX() && pacman.getCenterY() == p.getY()) {
				points.remove(i);
				score += 1;
				coin.play();
			}
		}

		if (score > bestScore) {
			bestScore = score;
			bestPlayer = null;
		}
	}

	public void pacmanBlockCollision() {
		pacman.changeDirection(blocks);
		pacman.blockCollision(blocks);
	}

	public void loadMap(int level) {
		blocks.clear();
		points.clear();
		ghosts.clear();
		pacman = null;
		switch (level) {
		case 1:
		case 2:
		case 3:
			currentBlock = block1;
			break;
		case 4:
		case 5:
		case 6:
			currentBlock = block2;
			break;
		case 7:
		case 8:
			currentBlock = block3;
			break;
		case 9:
		case 10:
			currentBlock = block4;
			break;
		}
		try {
			BufferedReader fo = new BufferedReader(new FileReader("maps/" + level + ".txt"));
			String a;
			char b;
			for (int i = 0; i < 16; i++) {// i is for axis x
				String mapLine = fo.readLine();
				for (int j = 0; j < 24; j++) {// j is for axis y
					a = mapLine.substring(j, j + 1);
					b = a.charAt(0);
					switch (b) {
					case '.':// point
						addPoint(j * 30, i * 30);
						break;
					case 'B':// block
						addBlock(j * 30, i * 30);
						break;
					case '-':// nothing
						break;
					case 'G':// ghost
						addGhost(j * 30, i * 30);
						addPoint(j * 30, i * 30);
						break;
					case 'P':// pacman
						pacman = new Pacman(j * 30, i * 30);
						break;
					}
				}
			}
			fo.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

		for (int i = 0; i < ghosts.size(); i++) {
			Ghost gh = (Ghost) ghosts.get(i);
			gh.chooseStartingDirection(pacman.getCenterX(), pacman.getCenterY());
		}

		Rectangle pacmanRect = new Rectangle(0, 0, 0, 0);
		// finding direction where pacman can
		// only for start
		for (int i = 0; i < blocks.size(); i++) {
			Block block = (Block) blocks.get(i);
			// up
			pacmanRect.setRect(pacman.getCenterX(), pacman.getCenterY() - 30, 30, 30);
			if (pacmanRect.intersects(block.getRect())) {
				pacman.setCanUp(false);
			}
			// down
			pacmanRect.setRect(pacman.getCenterX(), pacman.getCenterY() + 30, 30, 30);
			if (pacmanRect.intersects(block.getRect())) {
				pacman.setCanDown(false);
			}
			// left
			pacmanRect.setRect(pacman.getCenterX() - 30, pacman.getCenterY(), 30, 30);
			if (pacmanRect.intersects(block.getRect())) {
				pacman.setCanLeft(false);
			}
			// right
			pacmanRect.setRect(pacman.getCenterX() + 30, pacman.getCenterY(), 30, 30);
			if (pacmanRect.intersects(block.getRect())) {
				pacman.setCanRight(false);
			}
		}
	}

	public void reloadLevel() {// when pacman is dead
		lives--;
		if (lives != 0) {
			pacman.setPacmanToStartingPosition();
			for (int i = 0; i < ghosts.size(); i++) {
				Ghost gh = (Ghost) ghosts.get(i);
				gh.setGhostToStartingPosition();
				gh.chooseStartingDirection(pacman.getCenterX(), pacman.getCenterY());
			}
		}
	}

	public void restartGame() {
		level = 0;
		score = 0;
		lives = startLives;
		pacmanIsDead = false;
		pause = false;
		gameOverPlayed = false;
		points.clear();// this break the level loop in run()
	}

	public void loadBestPlayer() throws IOException {
		BufferedReader fo = new BufferedReader(new FileReader("data/bestplayer.txt"));
		bestPlayer = fo.readLine();
		String a = fo.readLine();
		bestScore = Integer.parseInt(a);
		fo.close();
	}

	public void writeBestPlayer() throws IOException {
		PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter("data/bestplayer.txt")));
		out.println(bestPlayer);
		out.println(bestScore);
		out.close();
	}
}